/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VirvoltRouteImport } from './routes/virvolt'
import { Route as IndexRouteImport } from './routes/index'

const VirvoltRoute = VirvoltRouteImport.update({
  id: '/virvolt',
  path: '/virvolt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/virvolt': typeof VirvoltRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/virvolt': typeof VirvoltRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/virvolt': typeof VirvoltRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/virvolt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/virvolt'
  id: '__root__' | '/' | '/virvolt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VirvoltRoute: typeof VirvoltRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/virvolt': {
      id: '/virvolt'
      path: '/virvolt'
      fullPath: '/virvolt'
      preLoaderRoute: typeof VirvoltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VirvoltRoute: VirvoltRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
