/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoireVirvoltRouteImport } from './routes/histoire-virvolt'
import { Route as IndexRouteImport } from './routes/index'

const HistoireVirvoltRoute = HistoireVirvoltRouteImport.update({
  id: '/histoire-virvolt',
  path: '/histoire-virvolt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/histoire-virvolt': typeof HistoireVirvoltRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/histoire-virvolt': typeof HistoireVirvoltRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/histoire-virvolt': typeof HistoireVirvoltRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/histoire-virvolt'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/histoire-virvolt'
  id: '__root__' | '/' | '/histoire-virvolt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoireVirvoltRoute: typeof HistoireVirvoltRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/histoire-virvolt': {
      id: '/histoire-virvolt'
      path: '/histoire-virvolt'
      fullPath: '/histoire-virvolt'
      preLoaderRoute: typeof HistoireVirvoltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoireVirvoltRoute: HistoireVirvoltRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
